### ISSUE TITLE
Capitalize name

### ISSUE THREAD

**Issue by kasvith** [alentar/rpms-server#28]
When user register with name, we need to capitalize first letter of each word

For example

jhon doe to Jhon Doe

**Comment by kasvith** [comment]
@edussuriyac can you solve this ?

**Comment by edussuriyac** [comment]
on it

**Comment by edussuriyac** [comment]
completed

**Comment by kasvith** [comment]
PR is not merged

**Comment by kasvith** [comment]
Closes by #35
