### ISSUE TITLE
Pages is minus when fetching all in a collection 

### ISSUE THREAD

**Issue by kasvith** [alentar/rpms-server#48]
## Description
In wards, users and others when query with `perPage = -1` the system return pages in minus value.
It should return a positive value

**Comment by namila007** [comment]
According to docs when rows=All it returns -1 
```
Name
rows-per-page-items
Default
[5,10,25,{"text":"All","value":-1}]
Type
Array
The default values for the rows-per-page dropdown```

[Link](https://vuetifyjs.com/en/components/data-tables)

**Comment by kasvith** [comment]
It should return -1,
**Please understand you need to fix the Server**, not the client
 **DO NOT MESS UP**

**Comment by kasvith** [comment]
Done with #56
